### ISSUE TITLE
Not a issue

### ISSUE THREAD

**Issue by JustTheJ** [Thundermaker300/StayShut#1]
Hi sorry I don't really know how to use Github and I wanted to talk to you and this is the only way that I saw it was possible to sort of comment on something. I would like to ask you something however i would like to ask you in a different setting, if you have a discord and could get the chance to talk to me my discord is Just_TheJ#2335. Thank you!

**Comment by Thundermaker300** [comment]
You can join the SCP:ET discord server and DM me through there, or email me (thunder@scpetgame.com).
